# Generated by Django 3.0.8 on 2020-07-14 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=500)),
                ('pub_date', models.DateField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_votes', models.IntegerField(default=0)),
                ('voted_date', models.DateField(verbose_name='voted date')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Songs')),
            ],
        ),
    ]
